# Generated by Django 3.0.3 on 2020-03-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20200318_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralnetwork',
            name='img',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
