# Generated by Django 3.0.3 on 2020-03-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0004_auto_20200318_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='cnn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
