# Generated by Django 3.1 on 2020-08-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_socialaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='date',
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.ImageField(upload_to='cycleGAN/upload/'),
        ),
    ]
