# Generated by Django 3.1 on 2020-10-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_auto_20200816_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.ImageField(upload_to='cycleGAN/'),
        ),
    ]
