# Generated by Django 3.1 on 2020-10-26 12:42

import ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_auto_20201019_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custommodel',
            name='file',
            field=models.FileField(upload_to=ai.models.get_upload_path, verbose_name='模型檔案'),
        ),
    ]
